'use client';

import type { Metadata } from "next";
import "@/styles/globals.css";
import ScrollToTop from "@/components/scrollToTop";
import Header from '@/components/header'
import Footer from '@/components/footer'
import { usePathname } from "next/navigation"

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname()
  return (
    <html lang="en">
      <body>
        { (path === '/') ?  
          <>
            {children}
          </> : 
          <>
            <ScrollToTop />
            <Header />
            {children}
            <Footer />
          </>
          }
      </body>
    </html>
  );
}
